version: 2

sources:
  - name: raw              # dbt'de source'u bu isimle çağıracaksın
    schema: gz_raw_data    # BigQuery dataset adı

    tables:
      - name: sales        # dbt'de gözükecek kısa isim
        identifier: raw_sales   # BigQuery'deki gerçek tablo adı

      - name: product
        identifier: raw_product

      - name: ship
        identifier: raw_ship